import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "th" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary
const translations: Record<Language, Record<string, string>> = {
  th: {
    // Navbar
    "nav.browse": "เรียกดู",
    "nav.myNovels": "นวนิยายของฉัน",
    "nav.orders": "คำสั่งซื้อ",
    "nav.admin": "ผู้ดูแล",
    "nav.cart": "ตะกร้า",
    "nav.logout": "ออกจากระบบ",
    "nav.login": "เข้าสู่ระบบ",
    "nav.points": "พอยท์",
    "nav.wallet": "กระเป๋าเงิน",
    "nav.signedInAs": "ลงชื่อเข้าใช้เป็น",
    "nav.viewOrders": "ดูคำสั่งซื้อ",
    "nav.backToCart": "กลับไปยังตะกร้า",

    // Home page
    "home.title": "ยินดีต้อนรับสู่ Ipe นิยายแปล",
    "home.subtitle": "Charcoal Gray Silver Gold Maya",
    "home.browse": "เรียกดูนวนิยาย",
    "home.myNovels": "นวนิยายของฉัน",
    "home.featured": "นวนิยายที่นิยม",
    "home.viewAll": "ดูทั้งหมด",
    "home.newReleases": "เพิ่งเข้าใหม่",
    "home.freeEpisodes": "ตอนฟรี",
    "home.noFeatured": "ยังไม่มีนวนิยายที่นิยม",
    "home.noNew": "ยังไม่มีเพิ่งเข้าใหม่",
    "home.noFree": "ยังไม่มีตอนฟรี",
    "home.welcomeTag": "ยินดีต้อนรับสู่",
    "home.free": "ฟรี",
    "home.featuredDesc": "นวนิยายที่นิยมเลือกอย่างหมันดุจากผู้อ่าน",
    "home.newReleasesDesc": "นวนิยายใหม่ล่าสุด",
    "home.freeEpisodesDesc": "อ่านฟรีที่คุณสามารถอ่านได้ทันที",
    "home.latestEpisodes": "ตอนที่อัปโหลดล่าสุด",
    "home.latestEpisodesDesc": "ตอนที่อัปโหลดล่าสุดจากนวนิยายต่างๆ",
    "home.episode": "ตอน",
    "home.noEpisodes": "ยังไม่มีตอนที่อัปโหลด",
    "home.learnMore": "เรียนรู้เพิ่มเติม",
    "home.ctaTitle": "พร้อมเริ่มอ่านหรือ",
    "home.ctaDescription": "สำรวจคนหาที่สุดของนวนิยายแปลไทยที่สมบูรณ์และหาความสนใจใหม่ที่คุณชอบคหรณ์",
    "home.browseAll": "เริ่มอ่านทั้งหมด",

    // Novels page
    "novels.title": "นวนิยาย",
    "novels.search": "ค้นหา...",
    "novels.noResults": "ไม่พบนวนิยาย",

    // Novel detail
    "novel.categories": "หมวดหมู่",
    "novel.description": "รายละเอียด",
    "novel.episodes": "ตอน",
    "novel.totalEpisodes": "จำนวนตอนทั้งหมด",
    "novel.freeEpisodes": "ตอนฟรี",
    "novel.paidEpisodes": "ตอนเสียค่าใช้",
    "novel.free": "ฟรี",
    "novel.purchased": "ซื้อแล้ว",
    "novel.inCart": "ในตะกร้า",
    "novel.addToCart": "เพิ่มลงตะกร้า",
    "novel.clearSelection": "ล้างการเลือก",
    "novel.notFound": "ไม่พบนวนิยาย",
    "novel.notFoundDesc": "นวนิยายที่คุณกำลังมองหาไม่มีอยู่หรือถูกลบแล้ว",
    "novel.backToNovels": "กลับไปยังนวนิยาย",

    // Cart
    "cart.title": "ตะกร้าสินค้า",
    "cart.empty": "ตะกร้าของคุณว่างอยู่",
    "cart.checkout": "ดำเนินการชำระเงิน",
    "cart.total": "รวมทั้งสิ้น",
    "cart.continueShopping": "เลือกซื้อสินค้าต่อ",
    "cart.orderSummary": "สรุปคำสั่งซื้อ",
    "cart.subtotal": "ยอดรวมสินค้า",
    "cart.applyCoupon": "ใช้คูปอง",
    "cart.redeemPoints": "แลกคะแนน",
    "cart.availablePoints": "คะแนนคงเหลือ",
    "cart.summary": "สรุปรายการ",
    "cart.proceedToPayment": "ดำเนินการชำระเงิน",
    "cart.availableCoupons": "คูปองที่ใช้ได้",
    "cart.couponCode": "รหัสคูปอง",
    "cart.pointsRedeemed": "ใช้พอยท์",
    "cart.discount": "ส่วนลด",

    // Payment
    "payment.transferAmount": "ยอดที่ต้องโอน",
    "payment.bank": "ธนาคาร",
    "payment.accountName": "ชื่อบัญชี",
    "payment.accountNumber": "เลขบัญชี",

    // Checkout
    "checkout.proceedToCheckout": "ไปที่หน้าชำระเงิน",

    // Orders
    "orders.title": "คำสั่งซื้อของฉัน",
    "orders.noOrders": "ไม่มีคำสั่งซื้อ",
    "orders.orderItems": "รายการสั่งซื้อ",
    "orders.paymentInfo": "ข้อมูลการชำระเงิน",
    "orders.paymentSlip": "สลิปการชำระเงิน",
    "orders.submitted": "ส่งแล้ว",

    // My Novels
    "myNovels.title": "นิยายของฉัน",
    "myNovels.noPurchases": "คุณยังไม่ได้ซื้อนิยายใด ๆ",
    "myNovels.download": "ดาวน์โหลด",
    "myNovels.ongoing": "กำลังดำเนินเรื่อง",
    "myNovels.finished": "จบแล้ว",

    // Points
    "points.title": "พอยท์ของฉัน",
    "points.subtitle": "รับและใช้พอยท์กับการซื้อแต่ละครั้ง",
    "points.currentBalance": "ยอดพอยท์ปัจจุบัน",
    "points.balanceDescription": "พอยท์ที่มีให้ใช้เพื่อรับส่วนลด",
    "points.rules": "กฎของพอยท์",
    "points.earnRate": "อัตราการรับพอยท์",
    "points.redeemRate": "อัตราการแลกพอยท์",
    "points.point": "พอยท์",
    "points.history": "ประวัติพอยท์",
    "points.date": "วันที่",
    "points.type": "ประเภท",
    "points.amount": "จำนวน",
    "points.balance": "ยอดคงเหลือ",
    "points.reference": "อ้างอิง",
    "points.earned": "ได้รับ",
    "points.redeemed": "ใช้แล้ว",
    "points.noHistory": "ยังไม่มีประวัติพอยท์",
    "points.browseLinkText": "เรียกดูนวนิยาย",
    "points.checkoutLinkText": "ไปที่ชำระเงิน",

    // Payment
    "payment.title": "ชำระเงิน",
    "payment.subtitle": "สแกน QR และอัปโหลดสลิปการชำระเงิน",
    "payment.orderSummary": "สรุปคำสั่งซื้อ",
    "payment.orderNumber": "หมายเลขคำสั่งซื้อ",
    "payment.items": "จำนวนรายการ",
    "payment.totalAmount": "จำนวนเงินที่ต้องชำระ",
    "payment.amount": "จำนวนเงินที่ต้องชำระ:",
    "payment.status": "สถานะการชำระเงิน:",
    "payment.qrPayment": "ชำระเงินผ่าน QR Payment",
    "payment.selectFile": "เลือกไฟล์สลิปเพื่อแนบการชำระเงิน",
    "payment.fileRequirements": "จำเป็นต้องแนบไฟล์สลิปการชำระเงิน",
    "payment.uploadButton": "ส่งคำสั่งซื้อ",
    "payment.scanAndPay": "สแกน QR และชำระเงิน",
    "payment.instructions": "วิธีการชำระเงิน:",
    "payment.step1": "ใช้แอปพลิเคชันธนาคารของคุณสแกน QR code",
    "payment.step2": "ยืนยันจำนวนเงิน ฿ และดำเนินการชำระเงิน",
    "payment.step3": "บันทึกหรือถ่ายภาพสลิปการชำระเงิน",
    "payment.uploadSlip": "อัปโหลดสลิปการชำระเงิน",
    "payment.clickToUpload": "คลิกเพื่ออัปโหลดสลิป",
    "payment.fileFormats": "รูปแบบที่รองรับ: JPG, PNG, PDF (สูงสุด 5MB)",
    "payment.fileSelected": "ไฟล์ที่เลือก",
    "payment.selectedFile": "ไฟล์ที่เลือก",
    "payment.scanQr": "สแกน QR",
    "payment.reviewTime": "เวลาตรวจสอบ",
    "payment.contactSupport": "ติดต่อฝ่ายสนับสนุน",
    "payment.alreadyApproved": "ชำระเงินสำเร็จแล้ว",
    "payment.approvedMessage": "ชำระเงินสำเร็จ ระบบอนุมัติคำสั่งซื้ออัตโนมัติแล้ว",
    "payment.autoApprovedOrderMessage": "ชำระเงินสำเร็จ ระบบอนุมัติคำสั่งซื้ออัตโนมัติแล้ว",
    "payment.pendingReviewOrderMessage": "ส่งสลิปแล้ว รอแอดมินตรวจสอบ",
    "payment.ocrErrorReviewMessage": "ส่งสลิปแล้ว แต่ระบบ OCR ขัดข้อง แอดมินจะตรวจสอบให้",
    "payment.duplicateReviewMessage": "พบความเสี่ยงสลิปซ้ำ รอแอดมินตรวจสอบ",
    "payment.lowConfidenceReviewMessage": "ส่งสลิปแล้ว ระบบอ่านข้อมูลไม่มั่นใจ รอแอดมินตรวจสอบ",
    "payment.slipReceived": "ส่งสลิปแล้ว",
    "payment.slipReceivedMessage": "ส่งสลิปแล้ว รอแอดมินตรวจสอบ",
    "payment.orderCreatedSuccess": "สร้างคำสั่งซื้อสำเร็จ",
    "order.createdSuccess": "สร้างคำสั่งซื้อสำเร็จ",
    "payment.submitSlip": "ส่งสลิป",
    "payment.slipSubmitted": "สลิปถูกส่งแล้ว",
    "payment.pendingReview": "รอการตรวจสอบจากผู้ดูแล",
    "payment.uploadNote": "หลังจากส่งสลิป ผู้ดูแลจะตรวจสอบและอนุมัติภายใน 1-2 ชั่วโมง",
    "payment.helpTitle": "ต้องการความช่วยเหลือ?",
    "payment.helpText": "หากคุณมีปัญหาในการชำระเงิน โปรดติดต่อเรา",
    "payment.slipUploadSuccess": "อัปโหลดสลิปสำเร็จ",
    "payment.slipUploadError": "ไม่สามารถอัปโหลดสลิป",
    "payment.invalidFileType": "ประเภทไฟล์ไม่ถูกต้อง",
    "payment.fileTooLarge": "ไฟล์มีขนาดใหญ่เกินไป",
    "payment.selectFileFirst": "กรุณาเลือกไฟล์ก่อน",
    "payment.uploadFailed": "ไม่สามารถอัปโหลดไฟล์",
    "payment.approved": "ชำระเงินได้รับการอนุมัติ",
    "payment.accessGranted": "ชำระเงินของคุณได้รับการอนุมัติแล้ว คุณสามารถเข้าถึงตอนที่ซื้อได้",
    "payment.rejected": "ชำระเงินถูกปฏิเสธ",
    "payment.rejectionReason": "เหตุผล",
    "payment.uploadNewSlip": "อัปโหลดสลิปใหม่",
    "payment.orderNotFound": "ไม่พบคำสั่งซื้อ",
    "payment.invalidOrder": "ลำดับที่คำสั่งซื้อไม่ถูกต้อง",
    "payment.pfNote": "กรุณาโอนเงินตามยอดที่แสดง แล้วอัปโหลดสลิปเพื่อยืนยันการชำระเงิน",
    "payment.uploadAndCheckout": "อัปโหลดสลิปและยืนยันคำสั่งซื้อ",
    "payment.bankDetails": "รายละเอียดธนาคาร",
    "payment.pdfNote": "ไฟล์ PDF จะถูกตรวจสอบด้วยตนเอง ไฟล์ JPG/PNG อาจได้รับการอนุมัติโดยอัตโนมัติ",
    "payment.autoApprovedMessage": "ชำระเงินได้รับการอนุมัติโดยอัตโนมัติ",
    "payment.manualReviewMessage": "ชำระเงินรอการตรวจสอบจากผู้ดูแล",
    "payment.ocrErrorMessage": "ไม่สามารถตรวจสอบสลิป กรุณาลองใหม่",
    "payment.duplicateMessage": "สลิปนี้ถูกส่งแล้ว กรุณาอัปโหลดสลิปใหม่",
     "payment.lowConfidenceMessage": "ไม่สามารถตรวจสลิปได้ชัดเจน กรุณาอัปโหลดสลิปใหม่",
    "cart.selectedItem": "รายการที่เลือก",

    // Admin
    "admin.dashboard": "แดชบอร์ด",
    "admin.novels": "นวนิยาย",
    "admin.episodes": "ตอน",
    "admin.categories": "หมวดหมู่",
    "admin.orders": "คำสั่งซื้อ",
    "admin.payments": "การชำระเงิน",
    "admin.entitlements": "สิทธิ์การเข้าถึง",
    "admin.settings": "การตั้งค่า",
    "admin.bulkUpload": "อัปโหลดจำนวนมาก",

    // Common
    "common.loading": "กำลังโหลด...",
    "common.error": "เกิดข้อผิดพลาด",
    "common.success": "สำเร็จ",
    "common.cancel": "ยกเลิก",
    "common.save": "บันทึก",
    "common.delete": "ลบ",
    "common.edit": "แก้ไข",
    "common.create": "สร้าง",
    "common.close": "ปิด",
    "common.notFound": "ไม่พบ",
    "common.back": "กลับ",
    "common.search": "ค้นหา",
    "common.filter": "กรอง",
    "common.sort": "เรียงลำดับ",
    "common.price": "ราคา",
    "common.free": "ฟรี",
    "common.paid": "เสียค่าใช้",
    "common.status": "สถานะ",
    "common.action": "การกระทำ",
    "common.confirm": "ยืนยัน",
    "common.yes": "ใช่",
    "common.no": "ไม่",
    "common.total": "รวม",
    "common.subtotal": "รวมย่อย",
    "common.tax": "ภาษี",
    "common.discount": "ส่วนลด",
    "common.apply": "ใช้",
    "common.remove": "ลบ",
    "common.add": "เพิ่ม",
    "common.update": "อัปเดต",
    "common.download": "ดาวน์โหลด",
    "common.upload": "อัปโหลด",
    "common.submit": "ส่ง",
    "common.reset": "รีเซ็ต",
    "common.previous": "ก่อนหน้า",
    "common.next": "ถัดไป",
    "common.page": "หน้า",
    "common.of": "ของ",
    "common.results": "ผลลัฎธ์",
    "common.pleaseSignIn": "กรุณาเข้าสู่ระบบเพื่อดำเนินการต่อ",
    "common.uploading": "กำลังอัปโหลด...",
    "common.startShopping": "เริ่มช้อปปิ้ง",
    "common.noData": "ไม่มีข้อมูล",
    "common.emptyState": "ไม่มีข้อมูล",
    "common.tryAgain": "ลองอีกครั้ง",
    "common.errorOccurred": "เกิดข้อผิดพลาด",
    "common.pleaseWait": "กรุณารอสักครู่...",
    "common.episode": "ตอน",
    "common.baht": "บาท",

    // Status labels
    "status.published": "ตีพิมพ์",
    "status.archived": "เก็บถาวร",
    "status.ongoing": "กำลังดำเนินการ",
    "status.finished": "เสร็จสิ้น",
    "status.pending": "รอดำเนินการ",
    "status.free": "ฟรี",
    "status.paid": "เสียค่าใช้",
    "status.episodes": "ตอน",
    "status.paidEpisodes": "ตอนที่ต้องชำระเงิน",
    "status.totalEpisodes": "ตอนทั้งหมด",
    "status.freeEpisodes": "ตอนที่อ่านฟรี",

    // Order workflow status (Badge 1)
    "order.status.pending": "รอดำเนินการ",
    "order.status.submitted": "รอดำเนินการ",
    "order.status.approved": "อนุมัติแล้ว",
    "order.status.rejected": "ถูกปฏิเสธ",

    // Payment status (Badge 2)
    "payment.status.unpaid": "ยังไม่ชำระเงิน",
    "payment.status.submitted": "ส่งแล้ว",
    "payment.status.approved": "ชำระเงินแล้ว",
    "payment.status.paid": "ชำระเงินแล้ว",
    "payment.status.rejected": "ถูกปฏิเสธ",

    // Unavailable novel
    "novel.unavailable": "ไม่สามารถดูนิยายเรื่องนี้ได้",
    "novel.unavailableDesc": "นิยายเรื่องนี้ถูกซ่อนหรือไม่พร้อมให้เข้าชมในขณะนี้",

    // Admin labels
    "admin.freeEpisode": "ตอนฟรี",
    "admin.paidEpisode": "ตอนเสียค่าใช้",
    "admin.pendingPayments": "การชำระเงินรอดำเนินการ",
    "admin.noPendingPayments": "ไม่มีการชำระเงินรอดำเนินการ",
    "admin.myNovels": "นิยายของฉัน",

    // Wallet
    "wallet.title": "กระเป๋าเงินของฉัน",
    "wallet.currentBalance": "ยอดเงินคงเหลือ",
    "wallet.topupRequests": "คำขอเติมเงิน",
    "wallet.requestTopup": "ขอเติมเงิน",
    "wallet.topupAmount": "จำนวนเงินที่ต้องการเติม",
    "wallet.createRequest": "สร้างคำขอ",
    "wallet.noTopups": "ยังไม่มีคำขอเติมเงิน",
    "wallet.recentTransactions": "รายการทำรายการล่าสุด",
    "wallet.noTransactions": "ยังไม่มีรายการทำรายการ",
    "wallet.uploadSlip": "อัปโหลดสลิป",
    "wallet.policyWarning": "นโยบายกระเป๋าเงิน",
    "wallet.policyMessage": "ยอดเงินในกระเป๋าใช้สำหรับซื้อสินค้าในระบบเท่านั้น • ยอดเงินที่เติมแล้วไม่สามารถถอนหรือขอคืนได้ • เมื่ออนุมัติแล้วจะไม่สามารถย้อนคืนได้",
    "wallet.shortWarning": "เติมเงินแล้วไม่สามารถถอนหรือขอคืนได้",
    "wallet.completeTopup": "ทำให้การเติมเงินสมบูรณ์",
    "wallet.pleaseFollowSteps": "โปรดทำตามขั้นตอนด้านล่างเพื่อให้การเติมเงินกระเป๋าสมบูรณ์",
    "wallet.topupAmountLabel": "จำนวนเงินที่ต้องการเติม:",
    "wallet.requestIdLabel": "ID คำขอ:",
    "wallet.statusLabel": "สถานะ:",
    "wallet.waitingForSlip": "รอการอัปโหลดสลิป",
    "wallet.step1ScanQR": "ขั้นตอนที่ 1: สแกน QR Code เพื่อชำระเงิน",
    "wallet.scanQRInstructions": "สแกน QR code นี้ด้วยแอปธนาคารของคุณและชำระเงินตรงตามจำนวน",
    "wallet.step2UploadSlip": "ขั้นตอนที่ 2: อัปโหลดสลิปการชำระเงิน",
    "wallet.afterPayingInstructions": "หลังจากชำระเงิน ให้ถ่ายภาพหรือบันทึกหน้าจอการยืนยันการชำระเงินและอัปโหลดด้านล่าง",
    "wallet.selectPaymentSlip": "เลือกรูปภาพสลิปการชำระเงิน",
    "wallet.acceptedFormats": "รูปแบบที่รองรับ: JPEG, PNG, PDF ขนาดสูงสุด: 5MB",
    "wallet.selected": "เลือกแล้ว:",
    "wallet.uploadSlipButton": "อัปโหลดสลิป",
    "wallet.uploading": "กำลังอัปโหลด...",
    "wallet.whatHappensNext": "จะเกิดอะไรขึ้นต่อไป?",
    "wallet.slipWillBeReviewed": "• สลิปของคุณจะถูกตรวจสอบโดยทีมผู้ดูแล",
    "wallet.youWillReceiveNotification": "• คุณจะได้รับการแจ้งเตือนเมื่อการเติมเงินของคุณได้รับการอนุมัติ",
    "wallet.balanceWillBeUpdated": "• ยอดเงินของคุณจะได้รับการอัปเดตทันทีหลังจากการอนุมัติ",
    "wallet.ifIssueWeWillContact": "• หากมีปัญหา เราจะติดต่อคุณพร้อมเหตุผลการปฏิเสธ",
    "wallet.backToWallet": "กลับไปยังกระเป๋าเงิน",
    "wallet.pleaseEnterValidAmount": "โปรดป้อนจำนวนเงินที่ถูกต้อง",
    "wallet.topupRequestCreated": "สร้างคำขอเติมเงินแล้ว โปรดดำเนินการชำระเงิน",
    "wallet.failedToCreateTopup": "ไม่สามารถสร้างคำขอเติมเงิน",
    "wallet.pleaseSelectFile": "โปรดเลือกไฟล์",
    "wallet.slipUploadedSuccessfully": "อัปโหลดสลิปสำเร็จ รอการตรวจสอบจากผู้ดูแล",
    "wallet.failedToUploadSlip": "ไม่สามารถอัปโหลดสลิป",
    "wallet.payWithWallet": "ชำระเงินด้วยกระเป๋าเงิน",
    "wallet.walletCheckoutSuccess": "ชำระเงินสำเร็จ! ได้รับสิทธิ์การเข้าถึงแล้ว",
    "wallet.walletCheckoutFailed": "การชำระเงินด้วยกระเป๋าเงินล้มเหลว",
    "wallet.insufficientBalance": "ยอดเงินในกระเป๋าไม่เพียงพอ",
    "wallet.walletTopups": "การเติมเงินกระเป๋า",
    "wallet.pendingTopups": "คำขอเติมเงินที่รอดำเนินการ",
    "wallet.noPendingTopups": "ไม่มีคำขอเติมเงินที่รอดำเนินการ",
    "wallet.requestedAmount": "จำนวนเงินที่ขอ:",
    "wallet.approvedAmount": "จำนวนเงินที่อนุมัติ:",
    "wallet.approve": "อนุมัติ",
    "wallet.reject": "ปฏิเสธ",
    "wallet.rejectionReason": "เหตุผลการปฏิเสธ:",
    "wallet.enterRejectionReason": "โปรดป้อนเหตุผลการปฏิเสธ",
    "wallet.topupApproved": "การเติมเงินได้รับการอนุมัติแล้ว",
    "wallet.topupRejected": "การเติมเงินถูกปฏิเสธ",
    "wallet.failedToApproveTopup": "ไม่สามารถอนุมัติการเติมเงิน",
    "wallet.failedToRejectTopup": "ไม่สามารถปฏิเสธการเติมเงิน",
    "wallet.scanQRToPayment": "สแกน QR เพื่อชำระเงิน",
    "wallet.qrPaymentHelper": "ชำระเงินตามจำนวนที่กรอก แล้วแนบสลิปก่อนส่งคำขอ",
    "payment.scanQRToPayment": "สแกน QR เพื่อชำระเงิน",
    "payment.qrPaymentHelper": "โอนตามยอดออเดอร์นี้ แล้วแนบสลิปก่อนยืนยันการชำระเงิน",
    "wallet.transactionTypeLabel": "ประเภทรายการ:",
    "wallet.credit": "เครดิต",
    "wallet.debit": "เดบิต",
    "wallet.amountLabel": "จำนวนเงิน:",
    "wallet.dateLabel": "วันที่:",

    // Wallet Policy - Full
    "wallet.policyTitle": "นโยบายกระเป๋าเงินและการเติมเงิน",
    "wallet.policyPoint1": "ยอดเงินในกระเป๋าใช้สำหรับซื้อสินค้าในระบบเท่านั้น",
    "wallet.policyPoint2": "ยอดเงินที่เติมแล้วไม่สามารถถอนหรือขอคืนได้",
    "wallet.policyPoint3": "กรุณาตรวจสอบจำนวนเงินและหลักฐานการชำระเงินก่อนยืนยันการเติมเงิน",
    "wallet.policyPoint4": "เมื่อคำขอเติมเงินได้รับการอนุมัติแล้ว จะไม่สามารถย้อนคืนหรือแก้ไขได้",
    "wallet.policyPoint5": "แต้มที่ใช้แลกส่วนลดจะถูกหักเมื่อคำสั่งซื้อสำเร็จเท่านั้น",
    "wallet.policyPoint6": "แต้มสะสมที่ได้รับจากคำสั่งซื้อสำเร็จถือเป็นที่สิ้นสุด และจะไม่มีการย้อนคืนอัตโนมัติ",
    "wallet.policyPoint7": "ในกรณีที่เกิดข้อผิดพลาดจากระบบ การตรวจสอบและแก้ไขจะดำเนินการโดยผู้ดูแลระบบตามความเหมาะสม",
    "myNovels.untitledNovel": "นิยายไม่มีชื่อ",
    "myNovels.published": "เผยแล้ว",
    "myNovels.archived": "เก็บไว้",
    "myNovels.noEpisodes": "ไม่มีตอนที่ใช้ได้",
    "myNovels.purchasedOn": "ซื้อเมื่อ",
    "myNovels.read": "อ่าน",
    "myNovels.readFileNotAvailable": "อ่าน (ไม่มีไฟล์)",

    // Sports Votes
    "sports.title": "ทายผลฟุตบอล",
    "sports.subtitle": "ใช้แต้มทายผลการแข่งขัน ลุ้นรับคูปองส่วนลด",
    "sports.points": "แต้มคงเหลือ",
    "sports.myRewards": "รางวัลของฉัน",
    "sports.activeMatches": "แมตช์ที่เปิดให้ทาย",
    "sports.noMatches": "ยังไม่มีแมตช์เปิดให้ทายตอนนี้",
    "sports.checkBack": "กลับมาดูใหม่ในช่วงการแข่งขันถัดไป",
    "sports.homeWin": "ทีมเหย้าชนะ",
    "sports.draw": "เสมอ",
    "sports.awayWin": "ทีมเยือนชนะ",
    "sports.voteSubmitted": "ส่งคำทายผลแล้ว",
    "sports.voteFailed": "ทายผลไม่สำเร็จ",
    "sports.copyAs": "คัดลอกคูปอง",
    "sports.alreadyUsed": "ใช้แล้ว",
    "sports.expired": "หมดอายุ",
    "sports.voided": "ถูกยกเลิก",
    "sports.available": "พร้อมใช้",
    "sports.deadline": "ปิดรับคำทายในอีก",
    "sports.closedForVoting": "ปิดรับคำทายแล้ว",
    "sports.cost": "ใช้",
    "sports.reward": "รางวัล",
    "sports.yourPrediction": "คำทายของคุณ",
    "sports.result": "ผลการแข่ง",
    "sports.pending": "รอประกาศผล",
    "sports.status": "สถานะ",
    "sports.couponCode": "รหัสคูปอง",
    "sports.discount": "ส่วนลด",
    "sports.minPurchase": "ซื้อขั้นต่ำ",
    "sports.expires": "หมดอายุ",
    "sports.confirmVote": "ยืนยันคำทาย",
    "sports.confirmVoteDescription": "ใช้ {cost} แต้ม เพื่อทายผลคู่นี้ใช่ไหม?",
    "sports.matchup": "คู่แข่งขัน",
    "sports.pointsUsed": "แต้มที่ใช้",
    "sports.homeWinLabel": "ชนะ",
    "sports.awayWinLabel": "ชนะ",
    "sports.drawLabel": "เสมอ",
    "sports.confirmVoteMessage": "ยืนยันใช้ {cost} แต้ม เพื่อทายว่า {home} ชนะ {away}?",
    "sports.confirmVoteDrawMessage": "ยืนยันใช้ {cost} แต้ม เพื่อทายว่า {home} กับ {away} เสมอ?",
    "sports.confirmVoteAwayMessage": "ยืนยันใช้ {cost} แต้ม เพื่อทายว่า {away} ชนะ {home}?",
    "sports.insufficientPoints": "แต้มไม่พอ ต้องใช้ {cost} แต้ม",
    "sports.tabs.openForVoting": "เปิดให้ทาย",
    "sports.tabs.myVotes": "ทายแล้ว",
    "sports.tabs.pending": "รอประกาศผล",
    "sports.tabs.myRewards": "รางวัลของฉัน",
    "sports.btnVote": "ทายผล",
    "sports.btnCancel": "ยกเลิก",
    "sports.btnConfirm": "ยืนยันคำทาย",
    "sports.btnCopyCoupon": "คัดลอกคูปอง",
    "sports.btnUseCoupon": "ไปใช้คูปอง",
    "sports.btnBrowseNovels": "เลือกนิยาย",
    "sports.pts": "แต้ม",
    "sports.hrs": "ชม.",
    "sports.mins": "นาที",
    "sports.won": "ทายถูก",
    "sports.lost": "ทายผิด",
    "sports.open": "เปิดให้ทาย",
    "sports.closed": "ปิดรับคำทาย",
    "sports.settled": "ประกาศผลแล้ว",
    "sports.cancelled": "ยกเลิกแล้ว",
    "sports.draft": "แบบร่าง",

    // Home - Finished Novels Section
    "home.finishedNovels": "นิยายจบแล้ว",
    "home.finishedDesc": "เรื่องที่จบสมบูรณ์แล้ว อ่านได้ยาวตั้งแต่ต้นจนจบ",
    "home.viewAllFinished": "ดูนิยายจบแล้วทั้งหมด",
    "home.finishedBadge": "จบแล้ว",

    // Wallet - Bonus Preview
    "wallet.loadingBonusInfo": "กำลังโหลดข้อมูลโบนัส...",
    "wallet.bonusLabel": "โบนัส",
    "wallet.requestedAmountLabel": "ยอดเติม",
    "wallet.totalToBeCredited": "ยอดที่จะเข้ากระเป๋า",
    "wallet.nextTierLabel": "ขั้นโบนัสถัดไป",
    "wallet.topupMoreForBonus": "เติมเพิ่มอีก ฿{amount} เพื่อรับโบนัสรวม ฿{bonus}",
    "wallet.noBonus": "ไม่มีโบนัส",

    // Novel Detail Page
    "novel.author": "ผู้แต่ง",
    "novel.noDescription": "ยังไม่มีคำอธิบาย",
    "novel.searchPlaceholder": "ค้นหาจากชื่อตอนหรือหมายเลขตอน...",
    "novel.newestFirst": "ล่าสุดก่อน",
    "novel.oldestFirst": "เก่าสุดก่อน",
    "novel.titleAZ": "ชื่อเรื่อง A-Z",
    "novel.titleZA": "ชื่อเรื่อง Z-A",
    "novel.unknownAuthor": "ไม่ระบุ",
    "novel.read": "อ่าน",
    "novel.episode": "ตอนที่",
    "novel.untitled": "ไม่มีชื่อ",

    // Cart
    "cart.pointsToRedeem": "จำนวนคะแนนที่ต้องการใช้",

    // Reader
    "reader.title": "อ่านนิยาย",
    "reader.backToNovel": "กลับไปยังรายละเอียด",
    "reader.previousEpisode": "ตอนก่อนหน้า",
    "reader.nextEpisode": "ตอนถัดไป",
    "reader.buyEpisode": "ซื้อบทนี้",
    "reader.confirmPurchase": "ยืนยันการซื้อบทนี้",
    "reader.confirmPurchaseDesc": "คุณต้องการซื้อบทนี้หรือไม่",
    "reader.price": "ราคา",
    "reader.walletBalance": "ยอดเงินในกระเป๋า",
    "reader.purchaseWithWalletOnly": "ซื้อรายบทต้องชำระด้วยกระเป๋าเงินเท่านั้น",
    "reader.couponNotAllowed": "คูปองไม่สามารถใช้กับการซื้อรายบทได้",
    "reader.alreadyPurchased": "ซื้อไปแล้ว",
    "reader.purchaseSuccess": "ซื้อสำเร็จแล้ว",
    "reader.insufficientBalance": "ยอดเงินในกระเป๋าไม่พอ",
    "reader.topupWallet": "เติมเงินกระเป๋า",
    "reader.lockedTitle": "บทนี้ต้องซื้อ",
    "reader.lockedDescription": "เพื่อดูเนื้อหาเต็มของบทนี้ คุณต้องซื้อด้วยกระเป๋าเงิน",
    "reader.freeEpisode": "บทฟรี",
    "reader.paidEpisode": "บทเสียค่าใช้",
    "reader.readNow": "อ่านเดี๋ยวนี้",
    "reader.fontSize": "ขนาดตัวอักษร",
    "reader.theme": "ธีม",
    "reader.light": "สว่าง",
    "reader.dark": "มืด",
    "reader.sepia": "เซเปีย",
    "reader.balanceAfterPurchase": "ยอดเงินหลังซื้อ",
    "reader.purchaseInfo": "หลังซื้อแล้ว คุณจะสามารถอ่านบทนี้ได้ถาวร",
    "reader.confirmBuy": "ยืนยันซื้อ",
    "reader.errorLoadingEpisode": "เกิดข้อผิดพลาดในการโหลดบท",
    "reader.noAccess": "คุณไม่มีสิทธิ์อ่านบทนี้",
  },
  en: {
    // Navbar
    "nav.browse": "Browse",
    "nav.myNovels": "My Novels",
    "nav.orders": "Orders",
    "nav.admin": "Admin",
    "nav.cart": "Cart",
    "nav.logout": "Logout",
    "nav.login": "Sign In",
    "nav.points": "Points",
    "nav.wallet": "Wallet",
    "nav.signedInAs": "Signed in as",
    "nav.viewOrders": "View Orders",
    "nav.backToCart": "Back to Cart",

    // Home page
    "home.title": "Welcome to Ipe นิยายแปล",
    "home.subtitle": "Charcoal Gray Silver Gold Maya",
    "home.browse": "Browse Novels",
    "home.myNovels": "My Novels",
    "home.featured": "Featured Novels",
    "home.viewAll": "View All",
    "home.newReleases": "New Releases",
    "home.freeEpisodes": "Free Episodes",
    "home.noFeatured": "No featured novels available yet",
    "home.noNew": "No new releases available yet",
    "home.noFree": "No free episodes available yet",
    "home.welcomeTag": "Welcome",
    "home.free": "Free",
    "home.featuredDesc": "Popular novels handpicked by our readers",
    "home.newReleasesDesc": "Latest releases",
    "home.freeEpisodesDesc": "Free episodes you can read instantly",
    "home.latestEpisodes": "Latest Uploaded Episodes",
    "home.latestEpisodesDesc": "Latest episodes uploaded from various novels",
    "home.episode": "Episode",
    "home.noEpisodes": "No episodes uploaded yet",
    "home.learnMore": "Learn More",
    "home.ctaTitle": "Ready to Start Reading?",
    "home.ctaDescription": "Browse our collection of translated novels and find your next favorite read.",
    "home.browseAll": "Browse All Novels",

    // Novels page
    "novels.title": "Novels",
    "novels.search": "Search...",
    "novels.noResults": "No novels found",

    // Novel detail
    "novel.categories": "Categories",
    "novel.episodes": "Episodes",
    "novel.totalEpisodes": "Total Episodes",
    "novel.freeEpisodes": "Free Episodes",
    "novel.paidEpisodes": "Paid Episodes",
    "novel.free": "Free",
    "novel.purchased": "Purchased",
    "novel.inCart": "In Cart",
    "novel.addToCart": "Add to Cart",
    "novel.clearSelection": "Clear Selection",
    "novel.notFound": "Novel Not Found",
    "novel.notFoundDesc": "The novel you're looking for doesn't exist or has been removed.",
    "novel.backToNovels": "Back to Novels",

    // Cart
    "cart.title": "Cart",
    "cart.empty": "Your cart is empty",
    "cart.checkout": "Checkout",
    "cart.total": "Total",
    "cart.continueShopping": "Continue Shopping",
    "cart.orderSummary": "Order Summary",
    "cart.subtotal": "Subtotal",
    "cart.applyCoupon": "Apply Coupon",
    "cart.redeemPoints": "Redeem Points",
    "cart.availablePoints": "Available Points",
    "cart.summary": "Order Summary",
    "cart.proceedToPayment": "Proceed to Payment",
    "cart.availableCoupons": "Available Coupons",
    "cart.couponCode": "Coupon Code",
    "cart.pointsRedeemed": "Points Redeemed",
    "cart.discount": "Discount",

    // Payment
    "payment.transferAmount": "Amount to Transfer",
    "payment.bank": "Bank",
    "payment.accountName": "Account Name",
    "payment.accountNumber": "Account Number",

    // Checkout
    "checkout.proceedToCheckout": "Go to Payment Page",

    // Orders
    "orders.title": "Orders",
    "orders.noOrders": "No orders",

    // My Novels
    "myNovels.title": "My Novels",
    "myNovels.noPurchases": "You haven't purchased any novels yet",
    "myNovels.download": "Download",
    "myNovels.untitledNovel": "Untitled Novel",
    "myNovels.published": "Published",
    "myNovels.archived": "Archived",
    "myNovels.noEpisodes": "No episodes available",
    "myNovels.purchasedOn": "Purchased on",
    "myNovels.read": "Read",
    "myNovels.readFileNotAvailable": "Read (File Not Available)",

    // Points
    "points.title": "My Points",
    "points.subtitle": "Earn and redeem points with every purchase",
    "points.currentBalance": "Current Balance",
    "points.balanceDescription": "Available points to redeem for discounts",
    "points.rules": "Points Rules",
    "points.earnRate": "Earn Rate",
    "points.redeemRate": "Redemption Rate",
    "points.point": "Point",
    "points.history": "Points History",
    "points.date": "Date",
    "points.type": "Type",
    "points.amount": "Amount",
    "points.balance": "Balance",
    "points.reference": "Reference",
    "points.earned": "Earned",
    "points.redeemed": "Redeemed",
    "points.noHistory": "No points history yet",
    "points.browseLinkText": "Browse Novels",
    "points.checkoutLinkText": "Go to Checkout",

    // Payment
    "payment.title": "Payment",
    "payment.subtitle": "Scan QR and upload payment slip",
    "payment.orderSummary": "Order Summary",
    "payment.orderNumber": "Order Number",
    "payment.items": "Items",
    "payment.totalAmount": "Total Amount",
    "payment.scanAndPay": "Scan QR and Pay",
    "payment.instructions": "Payment Instructions:",
    "payment.step1": "Use your bank app to scan the QR code",
    "payment.step2": "Confirm the amount and complete the payment",
    "payment.step3": "Save or take a photo of the payment slip",
    "payment.uploadSlip": "Upload Payment Slip",
    "payment.clickToUpload": "Click to upload slip",
    "payment.fileFormats": "Supported formats: JPG, PNG, PDF (max 5MB)",
    "payment.fileSelected": "File Selected",
    "payment.selectedFile": "File Selected",
    "payment.scanQr": "Scan QR",
    "payment.reviewTime": "Review Time",
    "payment.contactSupport": "Contact Support",
    "payment.alreadyApproved": "Payment Approved",
    "payment.approvedMessage": "Payment approved automatically! Your order is confirmed.",
    "payment.autoApprovedOrderMessage": "Payment approved automatically! Your order is confirmed.",
    "payment.pendingReviewOrderMessage": "Payment slip received. Waiting for admin review.",
    "payment.ocrErrorReviewMessage": "Payment slip received. OCR system error detected. Admin will review.",
    "payment.duplicateReviewMessage": "Duplicate slip detected. Waiting for admin review.",
    "payment.lowConfidenceReviewMessage": "Payment slip received. Low confidence reading. Waiting for admin review.",
    "payment.slipReceived": "Payment slip received",
    "payment.slipReceivedMessage": "Payment slip received. Waiting for admin review.",
    "payment.orderCreatedSuccess": "Order created successfully.",
    "order.createdSuccess": "Order created successfully.",
    "common.pleaseSignIn": "Please sign in to continue",
    "common.uploading": "Uploading...",
    "common.startShopping": "Start Shopping",
    "payment.submitSlip": "Submit Slip",
    "payment.slipSubmitted": "Slip Submitted",
    "payment.pendingReview": "Awaiting admin verification",
    "payment.uploadNote": "After submission, admin will verify and approve within 1-2 hours",
    "payment.helpTitle": "Need Help?",
    "payment.helpText": "If you have any issues with payment, please contact us",
    "payment.slipUploadSuccess": "Payment slip uploaded successfully",
    "payment.slipUploadError": "Failed to upload payment slip",
    "payment.invalidFileType": "Invalid file type",
    "payment.fileTooLarge": "File is too large",
    "payment.selectFileFirst": "Please select a file first",
    "payment.uploadFailed": "Failed to upload file",
    "payment.approved": "Payment Approved",
    "payment.accessGranted": "Your payment has been approved. You now have access to your purchased episodes.",
    "payment.rejected": "Payment Rejected",
    "payment.rejectionReason": "Reason",
    "payment.uploadNewSlip": "Upload New Payment Slip",
    "payment.orderNotFound": "Order Not Found",
    "payment.invalidOrder": "Invalid order ID",
    "payment.pfNote": "Please transfer the exact amount shown, then upload the payment slip to confirm the transaction",
    "payment.uploadAndCheckout": "Upload Slip and Confirm Order",
    "payment.bankDetails": "Bank Details",
    "payment.pdfNote": "PDF files will be reviewed manually. JPG/PNG files may be auto-approved.",
    "payment.autoApprovedMessage": "Payment auto-approved",
    "payment.manualReviewMessage": "Payment pending manual review",
    "payment.ocrErrorMessage": "Unable to verify payment slip. Please try again.",
    "payment.duplicateMessage": "This payment slip has already been submitted. Please upload a new one.",
    "payment.lowConfidenceMessage": "Unable to clearly verify the payment slip. Please upload a new one.",
    "cart.selectedItem": "Selected item",

    // Admin
    "admin.dashboard": "Dashboard",
    "admin.novels": "Novels",
    "admin.episodes": "Episodes",
    "admin.categories": "Categories",
    "admin.orders": "Orders",
    "admin.payments": "Payments",
    "admin.entitlements": "Entitlements",
    "admin.settings": "Settings",
    "admin.bulkUpload": "Bulk Upload",

    // Common
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.create": "Create",
    "common.close": "Close",
    "common.notFound": "Not Found",
    "common.back": "Back",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.sort": "Sort",
    "common.price": "Price",
    "common.free": "Free",
    "common.paid": "Paid",
    "common.status": "Status",
    "common.action": "Action",
    "common.confirm": "Confirm",
    "common.yes": "Yes",
    "common.no": "No",
    "common.total": "Total",
    "common.subtotal": "Subtotal",
    "common.tax": "Tax",
    "common.discount": "Discount",
    "common.apply": "Apply",
    "common.remove": "Remove",
    "common.add": "Add",
    "common.update": "Update",
    "common.download": "Download",
    "common.upload": "Upload",
    "common.submit": "Submit",
    "common.reset": "Reset",
    "common.previous": "Previous",
    "common.next": "Next",
    "common.page": "Page",
    "common.of": "of",
    "common.results": "Results",
    "common.noData": "No data",
    "common.emptyState": "Nothing here",
    "common.tryAgain": "Try Again",
    "common.errorOccurred": "An error occurred",
    "common.pleaseWait": "Please wait...",
    "common.episode": "Episode",
    "common.baht": "THB",

    // Status labels
    "status.published": "Published",
    "status.archived": "Archived",
    "status.ongoing": "Ongoing",
    "status.finished": "Finished",
    "status.pending": "Pending",
    "status.free": "Free",
    "status.paid": "Paid",

    // Order workflow status (Badge 1)
    "order.status.pending": "Pending",
    "order.status.submitted": "Pending",
    "order.status.approved": "Approved",
    "order.status.rejected": "Rejected",

    // Payment status (Badge 2)
    "payment.status.unpaid": "Unpaid",
    "payment.status.submitted": "Submitted",
    "payment.status.approved": "Paid",
    "payment.status.paid": "Paid",
    "payment.status.rejected": "Rejected",

    // Unavailable novel
    "novel.unavailable": "Novel Not Available",
    "novel.unavailableDesc": "This novel is hidden or not available at this time.",

    // Admin labels
    "admin.freeEpisode": "Free Episode",
    "admin.paidEpisode": "Paid Episode",
    "admin.pendingPayments": "Pending Payments",
    "admin.noPendingPayments": "No Pending Payments",

    // Wallet
    "wallet.title": "My Wallet",
    "wallet.currentBalance": "Current Balance",
    "wallet.topupRequests": "Top-up Requests",
    "wallet.requestTopup": "Request Top-up",
    "wallet.topupAmount": "Top-up Amount",
    "wallet.createRequest": "Create Request",
    "wallet.noTopups": "No top-up requests yet",
    "wallet.recentTransactions": "Recent Transactions",
    "wallet.noTransactions": "No transactions yet",
    "wallet.uploadSlip": "Upload Slip",
    "wallet.policyWarning": "Wallet Policy",
    "wallet.policyMessage": "Wallet balance is for purchasing items in the system only • Top-up amounts cannot be withdrawn or refunded • Once approved, transactions cannot be reversed",
    "wallet.shortWarning": "Top-ups cannot be withdrawn or refunded",
    "wallet.completeTopup": "Complete Your Top-up",
    "wallet.pleaseFollowSteps": "Please follow the steps below to complete your wallet top-up request.",
    "wallet.topupAmountLabel": "Top-up Amount:",
    "wallet.requestIdLabel": "Request ID:",
    "wallet.statusLabel": "Status:",
    "wallet.waitingForSlip": "waiting_for_slip",
    "wallet.step1ScanQR": "Step 1: Scan QR Code to Pay",
    "wallet.scanQRInstructions": "Scan this QR code with your mobile banking app and pay exactly",
    "wallet.step2UploadSlip": "Step 2: Upload Payment Slip",
    "wallet.afterPayingInstructions": "After paying, take a screenshot of the payment confirmation and upload it below.",
    "wallet.selectPaymentSlip": "Select Payment Slip Image",
    "wallet.acceptedFormats": "Accepted formats: JPEG, PNG, PDF. Max size: 5MB",
    "wallet.selected": "Selected:",
    "wallet.uploadSlipButton": "Upload Slip",
    "wallet.uploading": "Uploading...",
    "wallet.whatHappensNext": "What Happens Next?",
    "wallet.slipWillBeReviewed": "• Your slip will be reviewed by our admin team",
    "wallet.youWillReceiveNotification": "• You'll receive a notification when your top-up is approved",
    "wallet.balanceWillBeUpdated": "• Your wallet balance will be updated immediately after approval",
    "wallet.ifIssueWeWillContact": "• If there's an issue, we'll contact you with the rejection reason",
    "wallet.backToWallet": "Back to Wallet",
    "wallet.pleaseEnterValidAmount": "Please enter a valid amount",
    "wallet.topupRequestCreated": "Top-up request created. Please proceed with payment.",
    "wallet.failedToCreateTopup": "Failed to create top-up",
    "wallet.pleaseSelectFile": "Please select a file",
    "wallet.slipUploadedSuccessfully": "Slip uploaded successfully. Waiting for admin review.",
    "wallet.failedToUploadSlip": "Failed to upload slip",
    "wallet.payWithWallet": "Pay with Wallet",
    "wallet.walletCheckoutSuccess": "Payment successful! Access granted.",
    "wallet.walletCheckoutFailed": "Wallet checkout failed",
    "wallet.insufficientBalance": "Insufficient wallet balance",
    "wallet.walletTopups": "Wallet Top-ups",
    "wallet.pendingTopups": "Pending Top-ups",
    "wallet.noPendingTopups": "No pending top-ups",
    "wallet.requestedAmount": "Requested Amount:",
    "wallet.approvedAmount": "Approved Amount:",
    "wallet.approve": "Approve",
    "wallet.reject": "Reject",
    "wallet.rejectionReason": "Rejection Reason:",
    "wallet.enterRejectionReason": "Please enter rejection reason",
    "wallet.topupApproved": "Top-up approved successfully",
    "wallet.topupRejected": "Top-up rejected",
    "wallet.failedToApproveTopup": "Failed to approve top-up",
    "wallet.failedToRejectTopup": "Failed to reject top-up",
    "wallet.scanQRToPayment": "Scan QR to Pay",
    "wallet.qrPaymentHelper": "Pay the amount you entered, then attach the payment slip before submitting",
    "payment.scanQRToPayment": "Scan QR to Pay",
    "payment.qrPaymentHelper": "Transfer the order amount, then attach the payment slip before confirming payment",
    "wallet.transactionTypeLabel": "Transaction Type:",
    "wallet.credit": "Credit",
    "wallet.debit": "Debit",
    "wallet.amountLabel": "Amount:",
    "wallet.dateLabel": "Date:",

    // Wallet Policy - Full
    "wallet.policyTitle": "Wallet Policy and Top-up Terms",
    "wallet.policyPoint1": "Wallet balance is for purchasing items in the system only",
    "wallet.policyPoint2": "Top-up amounts cannot be withdrawn or refunded",
    "wallet.policyPoint3": "Please verify the amount and payment proof before confirming the top-up",
    "wallet.policyPoint4": "Once a top-up request is approved, it cannot be reversed or modified",
    "wallet.policyPoint5": "Redeemed points will only be deducted when the order is successfully completed",
    "wallet.policyPoint6": "Accumulated points from successful orders are final and will not be automatically reversed",
    "wallet.policyPoint7": "In case of system errors, verification and corrections will be handled by the administrator as appropriate",

    // Sports Votes
    "sports.title": "Football Predictions",
    "sports.subtitle": "Spend points to predict match results and win coupons",
    "sports.points": "Points Balance",
    "sports.myRewards": "My Rewards",
    "sports.activeMatches": "Active Matches",
    "sports.noMatches": "No matches available yet",
    "sports.checkBack": "Check back during the next tournament",
    "sports.homeWin": "Home Win",
    "sports.draw": "Draw",
    "sports.awayWin": "Away Win",
    "sports.voteSubmitted": "Vote submitted",
    "sports.voteFailed": "Vote failed",
    "sports.copyAs": "Copy Coupon",
    "sports.alreadyUsed": "Already Used",
    "sports.expired": "Expired",
    "sports.voided": "Voided",
    "sports.available": "Available",
    "sports.deadline": "Closes in",
    "sports.closedForVoting": "Closed for voting",
    "sports.cost": "Cost",
    "sports.reward": "Reward",
    "sports.yourPrediction": "Your prediction",
    "sports.result": "Result",
    "sports.pending": "Pending",
    "sports.status": "Status",
    "sports.couponCode": "Coupon Code",
    "sports.discount": "Discount",
    "sports.minPurchase": "Min Purchase",
    "sports.expires": "Expires",
    "sports.confirmVote": "Confirm Vote",
    "sports.confirmVoteDescription": "Use {cost} points to vote on this match?",
    "sports.matchup": "Matchup",
    "sports.pointsUsed": "Points Used",
    "sports.homeWinLabel": "wins",
    "sports.awayWinLabel": "wins",
    "sports.drawLabel": "draws",
    "sports.confirmVoteMessage": "Confirm using {cost} points to vote {home} wins {away}?",
    "sports.confirmVoteDrawMessage": "Confirm using {cost} points to vote {home} draws {away}?",
    "sports.confirmVoteAwayMessage": "Confirm using {cost} points to vote {away} wins {home}?",
    "sports.insufficientPoints": "Insufficient points. You need {cost} points",
    "sports.tabs.openForVoting": "Open for Voting",
    "sports.tabs.myVotes": "My Votes",
    "sports.tabs.pending": "Pending Results",
    "sports.tabs.myRewards": "My Rewards",
    "sports.btnVote": "Vote",
    "sports.btnCancel": "Cancel",
    "sports.btnConfirm": "Confirm Vote",
    "sports.btnCopyCoupon": "Copy Coupon",
    "sports.btnUseCoupon": "Use Coupon",
    "sports.btnBrowseNovels": "Browse Novels",
    "sports.pts": "pts",
    "sports.hrs": "hrs",
    "sports.mins": "mins",
    "sports.won": "Won",
    "sports.lost": "Lost",
    "sports.open": "Open",
    "sports.closed": "Closed",
    "sports.settled": "Settled",
    "sports.cancelled": "Cancelled",
    "sports.draft": "Draft",

    // Home - Finished Novels Section
    "home.finishedNovels": "Finished Novels",
    "home.finishedDesc": "Complete stories — read from start to finish",
    "home.viewAllFinished": "View All Finished",
    "home.finishedBadge": "Finished",

    // Wallet - Bonus Preview
    "wallet.loadingBonusInfo": "Loading bonus info...",
    "wallet.bonusLabel": "Bonus",
    "wallet.requestedAmountLabel": "Requested Amount",
    "wallet.totalToBeCredited": "Total to be Credited",
    "wallet.nextTierLabel": "Next Tier",
    "wallet.topupMoreForBonus": "Top up ฿{amount} more to get ฿{bonus} total bonus",
    "wallet.noBonus": "No Bonus",

    // Novel Detail Page
    "novel.author": "Author",
    "novel.noDescription": "No description available",
    "novel.searchPlaceholder": "Search by title or episode number...",
    "novel.newestFirst": "Newest First",
    "novel.oldestFirst": "Oldest First",
    "novel.titleAZ": "Title A-Z",
    "novel.titleZA": "Title Z-A",
    "novel.unknownAuthor": "Unknown",
    "novel.read": "Read",
    "novel.episode": "Episode",
    "novel.untitled": "Untitled",

    // Cart
    "cart.pointsToRedeem": "Points to redeem",

    // Reader
    "reader.title": "Read Novel",
    "reader.backToNovel": "Back to Details",
    "reader.previousEpisode": "Previous Episode",
    "reader.nextEpisode": "Next Episode",
    "reader.buyEpisode": "Buy This Episode",
    "reader.confirmPurchase": "Confirm Episode Purchase",
    "reader.confirmPurchaseDesc": "Are you sure you want to buy this episode?",
    "reader.price": "Price",
    "reader.walletBalance": "Wallet Balance",
    "reader.purchaseWithWalletOnly": "Episode purchase must be paid with wallet only",
    "reader.couponNotAllowed": "Coupons cannot be used for episode purchases",
    "reader.alreadyPurchased": "Already purchased",
    "reader.purchaseSuccess": "Purchase successful",
    "reader.insufficientBalance": "Insufficient wallet balance",
    "reader.topupWallet": "Top up Wallet",
    "reader.lockedTitle": "This Episode is Locked",
    "reader.lockedDescription": "To view the full content of this episode, you need to purchase it with your wallet",
    "reader.freeEpisode": "Free Episode",
    "reader.paidEpisode": "Paid Episode",
    "reader.readNow": "Read Now",
    "reader.fontSize": "Font Size",
    "reader.theme": "Theme",
    "reader.light": "Light",
    "reader.dark": "Dark",
    "reader.sepia": "Sepia",
    "reader.balanceAfterPurchase": "Balance After Purchase",
    "reader.purchaseInfo": "After purchase, you will be able to read this episode forever",
    "reader.confirmBuy": "Confirm Purchase",
    "reader.errorLoadingEpisode": "Error loading episode",
    "reader.noAccess": "You don't have access to read this episode",
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("th");

  // Load language from localStorage on mount
  useEffect(() => {
    const saved = localStorage.getItem("language") as Language | null;
    if (saved && (saved === "th" || saved === "en")) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations["en"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
